### ISSUE TITLE
30s delay on Azure boot: "Failed to get fabric address from DHCP"

### ISSUE THREAD

**Issue by dustymabe** [coreos/afterburn#652] opened 2021-12-10 15:10 UTC
## Bug #

When booting a Fedora CoreOS instance on azure there is a 30 second delay:

```
Dec 09 21:25:31 localhost.localdomain systemd[1]: sysroot-ostree-deploy-fedora\x2dcoreos-deploy-92d58206bcc345f7ede4a2385e64addc26e4714e4c2333b5e36ec84d524f6411.0.mount: Deactivated successfully.
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.477 WARN Failed to get fabric address from DHCP: maximum number of retries (60) reached
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.488 INFO Using fallback address
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.499 INFO Fetching http://168.63.129.16/?comp=versions: Attempt #1
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.508 INFO Fetch successful
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.518 INFO Fetching http://169.254.169.254/metadata/instance/compute/name?api-version=2017-08-01&format=text: Attempt #1
Dec 09 21:25:59 localhost.localdomain afterburn[685]: Dec 09 21:25:59.534 INFO Fetch successful
```

Basically it's using the fallback path added in https://github.com/coreos/afterburn/pull/145, which allows the boot to complete, but with a 30s delay. We need to add a fix here so we don't have a default 30s delay on our Azure boot.

### Operating System Version ##

Fedora CoreOS `35.20211208.dev.0` - dev build

### Afterburn Version ##

```
afterburn-5.1.0-1.fc35
```

### Environment ##

Azure

**Comment by prestist** [comment] 2023-01-12 17:51
Closing as a duplicate of #146

**Closed as not planned by prestist** 2023-01-12 17:51 UTC
